import '@fontsource/barlow/latin-400.css';
import '@fontsource/barlow/latin-500.css';
import '@fontsource/barlow-condensed/latin-700.css';
import '@fontsource/barlow-condensed/latin-800.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import 'lenis/dist/lenis.css';
import { createRoot } from 'react-dom/client';
import Experience from './components/orbital/Experience';
import './app/globals.css';
createRoot(document.getElementById('root')!).render(<Experience />);
