/** ATLAS offline optical resources. Reconstructed after workspace loss. */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { gzipSync, gunzipSync } from 'node:zlib';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPolygons, makeLandMask, makeRegionalCoast, makeCoastlines } from './optics-kernel.ts';

export const PROJECT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const SOURCE_PATH = 'public/atlas/data/vectors/globe-land.geojson';
export const SOURCE_SHA256 = '658908cec877ace15313918399ff7172a090aaa1f10ff7b920e418382a6aa007';
export const UPSTREAM_SHA256 = 'bcfb713f56fddf2fa32fd8f50799ce3e66d9ed3ce94337d82b6d4c5a8d4b9d6e';
export const OPTICS = Object.freeze([
  { filename: 'globe-land-mask-4096x2048.bin', bytes: 8388608, sha256: 'b7bc4bbce8c68ef66f2b168570ae74fe1c9479667a543683c99ceaefa2250397' },
  { filename: 'japan-coast-distance-2048x2048.bin', bytes: 4194304, sha256: '06db90e5a4bfd5c2ac118deecba89463393702ea4a9199d57466196c7cdd041f' },
  { filename: 'globe-coastlines-f32le.bin', bytes: 874464, sha256: 'ee867d4fb499d39e01d88703933ff4c4de9ecf182733dcf3d159bc5f5122eba5' },
]);
export const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const requireCondition = (condition, message) => { if (!condition) throw new Error(`ATLAS optics: ${message}`); };
function requireCanonical(raw, spec) {
  requireCondition(raw.length === spec.bytes, `${spec.filename}: wrong raw byte count`);
  requireCondition(sha256(raw) === spec.sha256, `${spec.filename}: non-canonical raw content`);
}
function littleEndianFloatBytes(values) {
  const bytes = Buffer.alloc(values.length * 4);
  for (let i = 0; i < values.length; i++) bytes.writeFloatLE(values[i], i * 4);
  return bytes;
}
export function deriveCanonical(sourceBytes) {
  requireCondition(sha256(sourceBytes) === SOURCE_SHA256, 'source GeoJSON changed; expected original geographic input');
  const polygons = readPolygons(JSON.parse(Buffer.from(sourceBytes).toString('utf8')));
  const mask = makeLandMask(polygons);
  const regional = makeRegionalCoast(polygons);
  const coast = makeCoastlines(polygons);
  try {
    const outputs = new Map([
      [OPTICS[0].filename, Buffer.from(mask.image.data)],
      [OPTICS[1].filename, Buffer.from(regional.image.data)],
      [OPTICS[2].filename, littleEndianFloatBytes(coast.getAttribute('position').array)],
    ]);
    for (const spec of OPTICS) requireCanonical(outputs.get(spec.filename), spec);
    return outputs;
  } finally { mask.dispose(); regional.dispose(); coast.dispose(); }
}
export async function verifyPackage(outputDir, sourceBytes, regenerated) {
  requireCondition(sha256(sourceBytes) === SOURCE_SHA256, 'source GeoJSON hash mismatch');
  const manifest = JSON.parse(await readFile(resolve(outputDir, 'DERIVATION.json'), 'utf8'));
  requireCondition(manifest.source.sha256 === SOURCE_SHA256, 'manifest source hash mismatch');
  requireCondition(manifest.upstream.originalGlobeSHA256 === UPSTREAM_SHA256, 'manifest upstream hash mismatch');
  requireCondition(manifest.generator.sha256 === sha256(await readFile(fileURLToPath(import.meta.url))), 'generator changed; regenerate metadata');
  requireCondition(manifest.kernel.sha256 === sha256(await readFile(resolve(PROJECT_ROOT, 'scripts/optics-kernel.ts'))), 'kernel changed; regenerate metadata');
  const results = [];
  for (const spec of OPTICS) {
    const record = manifest.outputs.find(item => item.filename === spec.filename);
    requireCondition(record?.bytes === spec.bytes && record?.sha256 === spec.sha256, `${spec.filename}: incorrect manifest raw declaration`);
    const raw = await readFile(resolve(outputDir, spec.filename));
    requireCanonical(raw, spec);
    if (regenerated) requireCondition(raw.equals(regenerated.get(spec.filename)), `${spec.filename}: generated bytes differ`);
    requireCondition(record.gzip?.filename === spec.filename + '.gz', `${spec.filename}: invalid gzip declaration`);
    const compressed = await readFile(resolve(outputDir, record.gzip.filename));
    requireCondition(compressed.length === record.gzip.bytes && sha256(compressed) === record.gzip.sha256, `${spec.filename}: packaged gzip hash mismatch`);
    requireCondition(gunzipSync(compressed).equals(raw), `${spec.filename}: gzip decodes to different content`);
    results.push({ ...spec, gzipBytes: compressed.length, canonicalRaw: true, gzipDecodesExactly: true });
  }
  return results;
}
export async function writePackage(outputDir, sourceBytes) {
  const rawOutputs = deriveCanonical(sourceBytes);
  await mkdir(outputDir, { recursive: true });
  const outputs = [];
  for (const spec of OPTICS) {
    const raw = rawOutputs.get(spec.filename);
    const compressed = gzipSync(raw, { level: 9 });
    const filename = spec.filename + '.gz';
    await writeFile(resolve(outputDir, spec.filename), raw);
    await writeFile(resolve(outputDir, filename), compressed);
    outputs.push({ ...spec, gzip: { filename, bytes: compressed.length, sha256: sha256(compressed) } });
  }
  const manifest = {
    schema: 'atlas-optics-derivation/v1',
    reconstructedAfterWorkspaceLoss: true,
    reconstructionProof: 'All three raw outputs match canonical SHA-256 identities recorded before workspace loss. This proves derived resource bytes; it does not restore lost browser evidence or the former generator source.',
    source: { path: SOURCE_PATH, sha256: SOURCE_SHA256, license: 'Natural Earth public domain', mapScale: '1:50,000,000', note: 'The legacy 50m dataset label denotes map scale, not 50-metre spatial precision.' },
    upstream: { repository: 'https://github.com/seiya058904/ai-web-experience-collection', commit: '186381f8da01aa8cf23771eb1514834d32b4d95c', path: 'experiences/atlas/src/world/globe.ts', originalGlobeSHA256: UPSTREAM_SHA256, license: 'MIT — Copyright (c) 2026 ATLAS contributors' },
    generator: { path: 'scripts/derive-optics.mjs', sha256: sha256(await readFile(fileURLToPath(import.meta.url))), node: process.version, zlib: process.versions.zlib },
    kernel: { path: 'scripts/optics-kernel.ts', sha256: sha256(await readFile(resolve(PROJECT_ROOT, 'scripts/optics-kernel.ts'))), note: 'Original numeric function bodies retained verbatim; exports and provenance header added.' },
    encoding: { rasterRowZero: 'south', rasterType: 'uint8', landSize: [4096, 2048], japanSize: [2048, 2048], japanBandTexels: 8, japanBounds: { west: 120, south: 24, east: 148, north: 49 }, coastlineType: 'IEEE754 float32 little-endian XYZ, kilometres, original 1.5 km display altitude', gzip: 'Level 9. Compressed byte encoding can vary across zlib versions; raw bytes are canonical. Verification checks packaged gzip hash and decoded equality, not regenerated gzip encoding.' },
    outputs,
  };
  await writeFile(resolve(outputDir, 'DERIVATION.json'), JSON.stringify(manifest, null, 2) + '\n');
  return verifyPackage(outputDir, sourceBytes, rawOutputs);
}
async function cli() {
  let check = false;
  let outputDir = resolve(PROJECT_ROOT, 'public/atlas/data/optics');
  const args = process.argv.slice(2);
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--check') check = true;
    else if (args[i] === '--output' && args[i + 1]) outputDir = resolve(args[++i]);
    else throw new Error(`Unknown argument: ${args[i]}`);
  }
  const source = await readFile(resolve(PROJECT_ROOT, SOURCE_PATH));
  const results = check ? await verifyPackage(outputDir, source, deriveCanonical(source)) : await writePackage(outputDir, source);
  process.stdout.write(JSON.stringify({ mode: check ? 'verified' : 'generated', outputDir, results }, null, 2) + '\n');
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await cli();
